name: CI Pipeline

on: [push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: echo "API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install uv
          uv sync

      - name: Run tests
        run: uv run pytest -v
